"""empty message

Revision ID: 256f8e17c829
Revises: 
Create Date: 2025-06-06 12:14:18.192824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256f8e17c829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_location', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_name'), ['event_name'], unique=False)

    op.create_table('formation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('degree_level', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formation_name'), ['name'], unique=True)

    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_name'), ['name'], unique=True)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('main_formation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_formation_id'], ['formation.id'], name='fk_student_main_formation_id'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='fk_student_school_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_main_formation_id'), ['main_formation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_school_id'), ['school_id'], unique=False)

    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('interaction_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='fk_interaction_event_id'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_interaction_student_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'event_id', name='uq_student_event_interaction')
    )
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_student_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_event_id'))

    op.drop_table('interaction')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_main_formation_id'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_name'))

    op.drop_table('school')
    with op.batch_alter_table('formation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formation_name'))

    op.drop_table('formation')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_name'))

    op.drop_table('event')
    # ### end Alembic commands ###
